// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/byt/categories/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/byt/categories/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/byt/categories/[id].put').default>>>>
    }
    '/api/admin/byt/categories': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/byt/categories/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/byt/categories/index.post').default>>>>
    }
    '/api/admin/byt/items/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/byt/items/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/byt/items/[id].put').default>>>>
    }
    '/api/admin/byt/items': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/byt/items/index.post').default>>>>
    }
    '/api/admin/collections/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/collections/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/collections/[id].put').default>>>>
    }
    '/api/admin/collections': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/collections/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/collections/index.post').default>>>>
    }
    '/api/admin/exhibits/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/exhibits/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/exhibits/[id].put').default>>>>
    }
    '/api/admin/exhibits': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/exhibits/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/exhibits/index.post').default>>>>
    }
    '/api/admin/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/login.post').default>>>>
    }
    '/api/admin/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/logout.post').default>>>>
    }
    '/api/admin/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/me.get').default>>>>
    }
    '/api/admin/news/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/news/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/news/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/news/[id].put').default>>>>
    }
    '/api/admin/news': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/news/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/news/index.post').default>>>>
    }
    '/api/admin/upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/upload.post').default>>>>
    }
    '/api/byt': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/byt.get').default>>>>
    }
    '/api/collections': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/collections.get').default>>>>
    }
    '/api/exhibits': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/exhibits.get').default>>>>
    }
    '/api/news/:slug': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/news/[slug].get').default>>>>
    }
    '/api/news': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/news/index.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}