// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 28.07.2026, 09:18:15
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/rammsstein/Desktop/museum nuxt theme/museum.nuxt.theme/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/rammsstein/Desktop/museum nuxt theme/museum.nuxt.theme/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/rammsstein/Desktop/museum nuxt theme/museum.nuxt.theme/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/rammsstein/Desktop/museum nuxt theme/museum.nuxt.theme/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/rammsstein/Desktop/museum nuxt theme/museum.nuxt.theme/app/plugins/**/*.{js,ts,mjs}","C:/Users/rammsstein/Desktop/museum nuxt theme/museum.nuxt.theme/app/composables/**/*.{js,ts,mjs}","C:/Users/rammsstein/Desktop/museum nuxt theme/museum.nuxt.theme/app/utils/**/*.{js,ts,mjs}","C:/Users/rammsstein/Desktop/museum nuxt theme/museum.nuxt.theme/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/rammsstein/Desktop/museum nuxt theme/museum.nuxt.theme/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/rammsstein/Desktop/museum nuxt theme/museum.nuxt.theme/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/rammsstein/Desktop/museum nuxt theme/museum.nuxt.theme/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;