// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/28/2026, 2:24:20 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/nikolay/Documents/museum nuxt theme/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/nikolay/Documents/museum nuxt theme/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/nikolay/Documents/museum nuxt theme/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/nikolay/Documents/museum nuxt theme/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/nikolay/Documents/museum nuxt theme/app/plugins/**/*.{js,ts,mjs}","/Users/nikolay/Documents/museum nuxt theme/app/composables/**/*.{js,ts,mjs}","/Users/nikolay/Documents/museum nuxt theme/app/utils/**/*.{js,ts,mjs}","/Users/nikolay/Documents/museum nuxt theme/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/nikolay/Documents/museum nuxt theme/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/nikolay/Documents/museum nuxt theme/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/nikolay/Documents/museum nuxt theme/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;